# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  autoVolumeSrc = {
    pname = "autoVolumeSrc";
    version = "d7f7962724b567a8409ef2898602f2c57abddf5a";
    src = fetchgit {
      url = "https://github.com/amanharwara/spicetify-autoVolume";
      rev = "d7f7962724b567a8409ef2898602f2c57abddf5a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-WquDmeaj+7M8DzGuHYOJgF6ifcs3vj3gIciZMaRQ3t4=";
    };
    date = "2020-02-16";
  };
  bloomSrc = {
    pname = "bloomSrc";
    version = "654cfed682b94613b0029997ffafc1eadccc5bef";
    src = fetchgit {
      url = "https://github.com/nimsandu/spicetify-bloom";
      rev = "654cfed682b94613b0029997ffafc1eadccc5bef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+pIf2N/yR8XwltRStSePUWDkm2x96hBbDrHbCF8a86k=";
    };
    date = "2025-05-20";
  };
  catppuccinSrc = {
    pname = "catppuccinSrc";
    version = "4294a61f54a044768c6e9db20e83c5b74da71091";
    src = fetchgit {
      url = "https://github.com/catppuccin/spicetify";
      rev = "4294a61f54a044768c6e9db20e83c5b74da71091";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OHsauoCjj99aoIbq78xQf1ehYtLpIcUde5DmZSJFCXI=";
    };
    date = "2024-05-20";
  };
  charlieS1103Src = {
    pname = "charlieS1103Src";
    version = "ab8fe9ccabc86477bc55a561fc532a0fa416d58c";
    src = fetchgit {
      url = "https://github.com/CharlieS1103/spicetify-extensions";
      rev = "ab8fe9ccabc86477bc55a561fc532a0fa416d58c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-14Q1hHowE0w9ynpjlM6rM079Hqu1WVy3dzarwCZSXHE=";
    };
    date = "2024-05-13";
  };
  comfySrc = {
    pname = "comfySrc";
    version = "2c22f3649a82e599be0e7eb506a0f83459caf9e8";
    src = fetchgit {
      url = "https://github.com/Comfy-Themes/Spicetify";
      rev = "2c22f3649a82e599be0e7eb506a0f83459caf9e8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KyhQuWotqcIHb9dU3PZnJe6QWN7LYbczR0W7IAxWGbg=";
    };
    date = "2025-04-03";
  };
  customAppsExtensionsSrc = {
    pname = "customAppsExtensionsSrc";
    version = "bb12c53dc11413e980ce3e40fbcec6f23b752003";
    src = fetchgit {
      url = "https://github.com/3raxton/spicetify-custom-apps-and-extensions";
      rev = "bb12c53dc11413e980ce3e40fbcec6f23b752003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7kVG5rAGKr8FTtXG7h0V2dBd8MBG5ntBwOjANN2Oheg=";
    };
    date = "2024-11-07";
  };
  dakshExtensions = {
    pname = "dakshExtensions";
    version = "d65abc6e869fdd456bd7ead83b5583926b57f103";
    src = fetchgit {
      url = "https://github.com/daksh2k/Spicetify-stuff";
      rev = "d65abc6e869fdd456bd7ead83b5583926b57f103";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v6dQcAaGPikHgeHmc8dYobomDej5V9SGeXpTbdbYtCY=";
    };
    date = "2025-08-27";
  };
  defaultDynamicSrc = {
    pname = "defaultDynamicSrc";
    version = "7ded763e056314dfbe56bba482405e2b3051c0cf";
    src = fetchgit {
      url = "https://github.com/JulienMaille/spicetify-dynamic-theme";
      rev = "7ded763e056314dfbe56bba482405e2b3051c0cf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9APA97OfP85otLBl7Ha89ddpFI8GsbPatW9JUw2rX/0=";
    };
    date = "2025-07-13";
  };
  draculaSrc = {
    pname = "draculaSrc";
    version = "97bf149e7afbe408509862591a57f1d8e2dfc5d7";
    src = fetchgit {
      url = "https://github.com/Darkempire78/Dracula-Spicetify";
      rev = "97bf149e7afbe408509862591a57f1d8e2dfc5d7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IS0A/5zTZou9yQJ0zpqAwiW2COt/TGoscN99WGFR9FA=";
    };
    date = "2022-02-14";
  };
  fluentSrc = {
    pname = "fluentSrc";
    version = "64b946af1ee4a5ed761d2f065c45b710e06bc123";
    src = fetchgit {
      url = "https://github.com/williamckha/spicetify-fluent";
      rev = "64b946af1ee4a5ed761d2f065c45b710e06bc123";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M6kczYmo0/+yL6iuMgkXECIQLOXDIR1aY8htS4KWjCE=";
    };
    date = "2024-05-02";
  };
  genreSrc = {
    pname = "genreSrc";
    version = "9cd089e46b95fde0f0d85ef738f21cde831a9d8e";
    src = fetchgit {
      url = "https://github.com/jeroentvb/spicetify-genre";
      rev = "9cd089e46b95fde0f0d85ef738f21cde831a9d8e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9xxfeMAU2c9K/peuzWkh7eUNN4R8i46bKjLOFI+Lz3A=";
    };
    date = "2024-03-01";
  };
  groupSessionSrc = {
    pname = "groupSessionSrc";
    version = "e6a2ce35589b9404e539c5778fa1c2efa53eefe6";
    src = fetchgit {
      url = "https://github.com/timll/spotify-group-session";
      rev = "e6a2ce35589b9404e539c5778fa1c2efa53eefe6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+DMtll5VGFkQIeeH+WklPow0iRzz0Sv1I/N8Gt4vzyQ=";
    };
    date = "2024-10-12";
  };
  hidePodcastsSrc = {
    pname = "hidePodcastsSrc";
    version = "ded693c1fb61cb9a7e89978db94e58ed2a16bf32";
    src = fetchgit {
      url = "https://github.com/theRealPadster/spicetify-hide-podcasts";
      rev = "ded693c1fb61cb9a7e89978db94e58ed2a16bf32";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/wVPIYzw40OlxxwL3kQhgUl0gcKmSX6HAGq1jojXFYo=";
    };
    date = "2025-08-03";
  };
  historySrc = {
    pname = "historySrc";
    version = "577e34f364127f18d917d2fe2e8c8f2a1af9f6ae";
    src = fetchgit {
      url = "https://github.com/einzigartigerName/spicetify-history";
      rev = "577e34f364127f18d917d2fe2e8c8f2a1af9f6ae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ORG1oNvMTJxrI3spfAuN+pCKTKvQfhqUIYT9NM1yZTs=";
    };
    date = "2021-05-20";
  };
  huhExtensionsSrc = {
    pname = "huhExtensionsSrc";
    version = "35f13148eeab8c995e85760c412993224591ebed";
    src = fetchgit {
      url = "https://github.com/huhridge/huh-spicetify-extensions";
      rev = "35f13148eeab8c995e85760c412993224591ebed";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qbO2J2LzNIGVyuW6VJcYqn2Q/CtIwLwkM/aVTscc+KY=";
    };
    date = "2025-07-24";
  };
  lastfmSrc = {
    pname = "lastfmSrc";
    version = "d2f1d3c1e286d789ddfa002f162405782d822c55";
    src = fetchgit {
      url = "https://github.com/LucasBares/spicetify-last-fm";
      rev = "d2f1d3c1e286d789ddfa002f162405782d822c55";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/C4Y3zuSAEwhMXCRG2/4b5oWfGz/ij6wu0B+CpuJKXs=";
    };
    date = "2022-11-20";
  };
  localFilesSrc = {
    pname = "localFilesSrc";
    version = "1bfd2fc80385b21ed6dd207b00a371065e53042e";
    src = fetchgit {
      url = "https://github.com/hroland/spicetify-show-local-files";
      rev = "1bfd2fc80385b21ed6dd207b00a371065e53042e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-neKR2WaZ1K10dZZ0nAKJJEHNS56o8vCpYpi+ZJYJ/gU=";
    };
    date = "2022-04-12";
  };
  marketplaceSrc = {
    pname = "marketplaceSrc";
    version = "bacdf424cc5d46d60703f746fdd96a9b1d6edc72";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-marketplace";
      rev = "bacdf424cc5d46d60703f746fdd96a9b1d6edc72";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6mHi0qt6eyEqjbkFjMBP4POkxYGIw3M5GZheoHpc3t8=";
    };
    date = "2025-09-01";
  };
  nameThatTuneSrc = {
    pname = "nameThatTuneSrc";
    version = "de72806ca6f3457853e937808a0877b0bb4db80c";
    src = fetchgit {
      url = "https://github.com/theRealPadster/name-that-tune";
      rev = "de72806ca6f3457853e937808a0877b0bb4db80c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iCg2kv+SeWKvARv+g9grp+ixAmV2WSnbWgV/OJ3H2Rk=";
    };
    date = "2025-07-01";
  };
  nordSrc = {
    pname = "nordSrc";
    version = "caab9e0afaa6d228b4d73ae6c4c40dd56d3888c7";
    src = fetchgit {
      url = "https://github.com/Tetrax-10/Nord-Spotify";
      rev = "caab9e0afaa6d228b4d73ae6c4c40dd56d3888c7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-HlywN6a6nQ9Z1Rsg3crkFQuY+npXaN4Qo9cjPLfeqmw=";
    };
    date = "2023-06-06";
  };
  officialSrc = {
    pname = "officialSrc";
    version = "c2d2ef33aa889fac004b879c1d25afedfd65f389";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-cli";
      rev = "c2d2ef33aa889fac004b879c1d25afedfd65f389";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-jGLocXwQavUqs15AOf7paBXRF1/kLYRhm04Gl82gL4w=";
    };
    date = "2025-09-01";
  };
  officialThemes = {
    pname = "officialThemes";
    version = "726097a544172523cdae15da8d3c84032aec8c3b";
    src = fetchgit {
      url = "https://github.com/spicetify/spicetify-themes";
      rev = "726097a544172523cdae15da8d3c84032aec8c3b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mQgkmbkgzfWlT1iv4jB/cw95v4q0/+57B9rgmezAY34=";
    };
    date = "2025-08-17";
  };
  omniSrc = {
    pname = "omniSrc";
    version = "253ae45d2cac2dc3d92a43193ea8f6d9e7e1d3aa";
    src = fetchgit {
      url = "https://github.com/getomni/spicetify";
      rev = "253ae45d2cac2dc3d92a43193ea8f6d9e7e1d3aa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5II+4096fOcCA7J4XZfIHSse+3/YJ+EY5KW3GXl+dn8=";
    };
    date = "2023-01-20";
  };
  onekoSrc = {
    pname = "onekoSrc";
    version = "589a8cc3a3939b8c9fc4f2bd087ed433e9af5002";
    src = fetchgit {
      url = "https://github.com/kyrie25/spicetify-oneko";
      rev = "589a8cc3a3939b8c9fc4f2bd087ed433e9af5002";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lestrf4sSwGbBqy+0J7u5IoU6xNKHh35IKZxt/phpNY=";
    };
    date = "2024-07-06";
  };
  orchisSrc = {
    pname = "orchisSrc";
    version = "5bf3fcf0696514dcf3e95f4ae3fd00261ccc5dcc";
    src = fetchgit {
      url = "https://github.com/canbeardig/Spicetify-Orchis-Colours-v2";
      rev = "5bf3fcf0696514dcf3e95f4ae3fd00261ccc5dcc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9cU2Wlg5W57JpBfzIOXvpRYI8Q3CsH+UsdjQseTr9bs=";
    };
    date = "2022-05-20";
  };
  playlistIconsSrc = {
    pname = "playlistIconsSrc";
    version = "7378f0a823eabf1b1a5f9b6237002dcd4631a27a";
    src = fetchgit {
      url = "https://github.com/jeroentvb/spicetify-playlist-icons";
      rev = "7378f0a823eabf1b1a5f9b6237002dcd4631a27a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-EBl8mSofEdjAoHugziLDF/5FRSoCfpW9wIj3HH4iwkA=";
    };
    date = "2024-12-01";
  };
  powerBarSrc = {
    pname = "powerBarSrc";
    version = "648e33489abe106488db6fa791cd6bc6a3169035";
    src = fetchgit {
      url = "https://github.com/jeroentvb/spicetify-power-bar";
      rev = "648e33489abe106488db6fa791cd6bc6a3169035";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-RMaE8OQCTAHVZdyTnOvRUg9Mxu0KKZC/wELiq9aStJQ=";
    };
    date = "2025-02-26";
  };
  retroBlurSrc = {
    pname = "retroBlurSrc";
    version = "685cf3aea4ed1a4d82f687293f0efb5baa1aec06";
    src = fetchgit {
      url = "https://github.com/Motschen/Retroblur";
      rev = "685cf3aea4ed1a4d82f687293f0efb5baa1aec06";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YAOmeSAxD0qR8Y7t+HOBoTCJtiJNfveJCmiptfg25OE=";
    };
    date = "2024-06-08";
  };
  spotifyCanvasSrc = {
    pname = "spotifyCanvasSrc";
    version = "02318f300fc5dde257af9348c8c752f7d566ccff";
    src = fetchgit {
      url = "https://github.com/itsmeow/Spicetify-Canvas";
      rev = "02318f300fc5dde257af9348c8c752f7d566ccff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SNyBbFKBy4yOEVa1iFPqH1cr2pqfdIGu72ErtjR1yUs=";
    };
    date = "2025-07-25";
  };
  spotifyNoPremiumSrc = {
    pname = "spotifyNoPremiumSrc";
    version = "6b145fb84e16cdaea8f06aef4d1cfc0d6f5898e5";
    src = fetchgit {
      url = "https://github.com/Daksh777/SpotifyNoPremium";
      rev = "6b145fb84e16cdaea8f06aef4d1cfc0d6f5898e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pjIBh40SnUgyAKGwVRKod2ac8+uqGJ2WSTnOYc9UnGA=";
    };
    date = "2024-11-11";
  };
  spotifywmSrc = {
    pname = "spotifywmSrc";
    version = "8624f539549973c124ed18753881045968881745";
    src = fetchgit {
      url = "https://github.com/dasJ/spotifywm";
      rev = "8624f539549973c124ed18753881045968881745";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AsXqcoqUXUFxTG+G+31lm45gjP6qGohEnUSUtKypew0=";
    };
    date = "2022-10-25";
  };
  starRatingsSrc = {
    pname = "starRatingsSrc";
    version = "d4dca612ab496dbe969ff1fe043e2b4ec0db6010";
    src = fetchgit {
      url = "https://github.com/brimell/spicetify-star-ratings";
      rev = "d4dca612ab496dbe969ff1fe043e2b4ec0db6010";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OwwnxMBU5NACdyojWzuMvKZ8vJoFQdPWXB/pzPexwas=";
    };
    date = "2025-08-23";
  };
  startPageSrc = {
    pname = "startPageSrc";
    version = "75bd17ba1c9a19730f14529fb18857d7b9c7c12e";
    src = fetchgit {
      url = "https://github.com/Resxt/startup-page";
      rev = "75bd17ba1c9a19730f14529fb18857d7b9c7c12e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+Th5o00c3Y8U+Y/RGmRSkWWp97YCoCJmoESFLZf9dwM=";
    };
    date = "2024-02-15";
  };
  tetraxSrc = {
    pname = "tetraxSrc";
    version = "26c608469889a415534e29d5382b3039aed1d426";
    src = fetchgit {
      url = "https://github.com/Tetrax-10/Spicetify-Extensions";
      rev = "26c608469889a415534e29d5382b3039aed1d426";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XXjUbbH7fZXxTyK4+Vgt/MELWehPAMxG8auGCFXiQjg=";
    };
    date = "2025-05-31";
  };
}
