name: "Update Spicetify Packages"

on:
  schedule:
    - cron:  '19 18 * * *'
  push:
    paths:
      - 'pkgs/nvfetcher.toml'
  repository_dispatch:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NIXPKGS_ALLOW_UNFREE: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Run nvfetcher
      run: |
        nix run github:berberman/nvfetcher -- -o pkgs/_sources -c pkgs/nvfetcher.toml

    - name: Show flake metadata
      run: nix flake metadata --impure

    - name: Build nix packages
      run: | 
        nix build .#checks.x86_64-linux.default --impure -v
        git fetch origin master
    
    - name: Push updates
      if: ${{ success() }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Bump Spicetify Packages"
        file_pattern: "pkgs/_sources/"
